#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
feh --bg-center .local/share/wallpapes/wall.jpg &
mpd &
picom -b &
setxkbmap -option grp:alt_shift_toggle us,ru &
$HOME/.config/polybar/launch.sh
#xrandr --output HDMI-0 --mode 1280x1024 --right-of eDP-1-0 --output eDP-1-0 --primary --auto &

bspc monitor -d 1 2 3 4 5 6
#bspc monitor HDMI-0 -d 4 5 6
#bspc monitor eDP-1-0 -d 1 2 3

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
